### ISSUE TITLE
Incompatibilities during installation

### ISSUE THREAD

**Issue by avekifes** [dgtlmoon/pyppeteer-ng#3]
I'm getting upon pip install:

> ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
> aiosqlite 0.20.0 requires typing_extensions>=4.0, but you have typing-extensions 3.10.0.2 which is incompatible.
> asyncpraw 7.7.1 requires aiofiles<1, but you have aiofiles 23.2.1 which is incompatible.
> asyncpraw 7.7.1 requires aiosqlite<=0.17.0, but you have aiosqlite 0.20.0 which is incompatible.
> textual 0.52.1 requires typing-extensions<5.0.0,>=4.4.0, but you have typing-extensions 3.10.0.2 which is incompatible.

Python version: 3.11.1
OS: Windows 10

**Comment by dgtlmoon** [comment]
you have some other package installed which is conflicting

**Comment by dgtlmoon** [comment]
this is also not the whole log... so i cant see everything

**Comment by gety9** [comment]
@avekifes did you solve the issue?

**Comment by dgtlmoon** [comment]
Just bumped pyppeteer-ng to use a newer typing_extensions
